name: runtime_digital_fingerprint
description: A Dart package for fingerprinting machines
version: 1.0.0
homepage: https://github.com/open-runtime/runtime_digital_fingerprint

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
