name: test on multiple platforms

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: 3.4.3

    - name: Test
      working-directory: ${{ github.workspace }}
      run: dart test
